module.exports = {
  components: [
    // 'virtual',
    'keyboard',
    // 'mousewheel',
    'navigation',
    'pagination',
    // 'scrollbar',
    // 'parallax',
    // 'zoom',
    'lazy',
    'controller',
    'a11y',
    // 'history',
    // 'hash-navigation',
    'autoplay',
    // 'effect-fade',
    // 'effect-cube',
    // 'effect-flip',
    // 'effect-coverflow',
    'thumbs',
  ],
  themeColor: '#2B2823',
  colors: {
    white: '#ffffff',
    black: '#000000',
  },
};
